apiVersion: v1
kind: Service
metadata:
  name: {{ template "tca.fullname" . }}-gateway
  labels:
    k8s-app: {{ template "tca.fullname" . }}-gateway
    app: {{ template "tca.name" . }}
    chart: {{ template "tca.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.tca.gateway.service.type }}
  {{- if and .Values.tca.gateway.service.clusterIP (eq .Values.tca.gateway.service.type "ClusterIP") }}
  clusterIP: {{ .Values.tca.gateway.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.tca.gateway.service.type "LoadBalancer") (eq .Values.tca.gateway.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.tca.gateway.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.tca.gateway.service.type "LoadBalancer") (not (empty .Values.tca.gateway.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.tca.gateway.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.tca.gateway.service.type "LoadBalancer") (not (empty .Values.tca.gateway.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.tca.gateway.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.tca.gateway.service.ports.http }}
    protocol: TCP
    targetPort: http
    {{- if (and (or (eq .Values.tca.gateway.service.type "NodePort") (eq .Values.tca.gateway.service.type "LoadBalancer")) (not (empty .Values.tca.gateway.service.nodePorts.http))) }}
    nodePort: {{ .Values.tca.gateway.service.nodePorts.http }}
    {{- else if eq .Values.tca.gateway.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  {{- if .Values.tca.gateway.service.ports.https }}
  - name: https
    port: {{ .Values.tca.gateway.service.ports.https }}
    protocol: TCP
    targetPort: {{ .Values.tca.gateway.service.httpsTargetPort }}
    {{- if (and (or (eq .Values.tca.gateway.service.type "NodePort") (eq .Values.tca.gateway.service.type "LoadBalancer")) (not (empty .Values.tca.gateway.service.nodePorts.https))) }}
    nodePort: {{ .Values.tca.gateway.service.nodePorts.https }}
    {{- else if eq .Values.tca.gateway.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  {{- end }}
  selector:
    k8s-app: {{ template "tca.fullname" . }}-gateway
    release: {{ .Release.Name }}
