apiVersion: v1
kind: Service
metadata:
  name: {{ template "tca.fullname" . }}-web
  labels:
    k8s-app: {{ template "tca.fullname" . }}-web
    app: {{ template "tca.name" . }}
    chart: {{ template "tca.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.tca.web.service.ports.http }}
    protocol: TCP
    targetPort: http
    nodePort: {{ .Values.tca.web.service.nodePorts.http }}
  {{- if .Values.tca.web.service.ports.https }}
  - name: https
    port: {{ .Values.tca.web.service.ports.https }}
    protocol: TCP
    targetPort: {{ .Values.tca.web.service.httpsTargetPort }}
    nodePort: {{ .Values.tca.web.service.nodePorts.https }}
  {{- end }}
  selector:
    k8s-app: {{ template "tca.fullname" . }}-web
    release: {{ .Release.Name }}
