apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: {{ template "tca.fullname" . }}-main-server
    app: {{ template "tca.name" . }}
    chart: {{ template "tca.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "tca.fullname" . }}-main-server
spec:
  selector:
    matchLabels:
      k8s-app: {{ template "tca.fullname" . }}-main-server
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ template "tca.fullname" . }}-main-server
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.tca.podAntiAffinity.enable }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "{{ .Values.tca.podAntiAffinity.topologyKey }}"
                labelSelector:
                  matchLabels:
                    k8s-app: {{ template "tca.fullname" . }}-main-server
                    release: {{ .Release.Name }}
      {{- end }}
      containers:
        - name: {{ template "tca.fullname" . }}-main-server
          image: "{{ .Values.tca.main.image.repository }}:{{ .Values.tca.main.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["gunicorn"]
          args: ["codedog.wsgi", "-c", "main.gunicorn.conf.py"]
          envFrom:
            - configMapRef:
                name: main-env
          env:
            - name: _HASH_CONFIG_
              value: {{ include (print $.Template.BasePath "/main/configmap.yaml") . | sha256sum }}
          ports:
            - name: http
              containerPort: {{ .Values.tca.main.server.port }}
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '20'
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: {{ .Values.tca.main.server.port }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: {{ .Values.tca.main.server.port }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
          resources:
{{ toYaml .Values.tca.main.resources | indent 12 }}
---
{{- if .Values.tca.main.server.autoscaling }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "tca.fullname" . }}-main-server
  labels:
    k8s-app: {{ template "tca.fullname" . }}-main-server
    app: {{ template "tca.name" . }}
    chart: {{ template "tca.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "tca.fullname" . }}-main-server
  minReplicas: {{ .Values.tca.main.server.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.tca.main.server.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.tca.main.server.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.tca.main.server.autoscaling.targetMemory }}
    {{- end }}
    {{- if .Values.tca.main.server.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.tca.main.server.autoscaling.targetCPU }}
    {{- end }}
{{- end }}
